(##namespace ("github.com/feeley/pyffi#"
              pydis
              PYOPS
              PYOP_POP_TOP
              PYOP_ROT_TWO
              PYOP_ROT_THREE
              PYOP_DUP_TOP
              PYOP_DUP_TOP_TWO
              PYOP_ROT_FOUR
              PYOP_NOP
              PYOP_UNARY_POSITIVE
              PYOP_UNARY_NEGATIVE
              PYOP_UNARY_NOT
              PYOP_UNARY_INVERT
              PYOP_BINARY_MATRIX_MULTIPLY
              PYOP_INPLACE_MATRIX_MULTIPLY
              PYOP_BINARY_POWER
              PYOP_BINARY_MULTIPLY
              PYOP_BINARY_MODULO
              PYOP_BINARY_ADD
              PYOP_BINARY_SUBTRACT
              PYOP_BINARY_SUBSCR
              PYOP_BINARY_FLOOR_DIVIDE
              PYOP_BINARY_TRUE_DIVIDE
              PYOP_INPLACE_FLOOR_DIVIDE
              PYOP_INPLACE_TRUE_DIVIDE
              PYOP_RERAISE
              PYOP_WITH_EXCEPT_START
              PYOP_GET_AITER
              PYOP_GET_ANEXT
              PYOP_BEFORE_ASYNC_WITH
              PYOP_END_ASYNC_FOR
              PYOP_INPLACE_ADD
              PYOP_INPLACE_SUBTRACT
              PYOP_INPLACE_MULTIPLY
              PYOP_INPLACE_MODULO
              PYOP_STORE_SUBSCR
              PYOP_DELETE_SUBSCR
              PYOP_BINARY_LSHIFT
              PYOP_BINARY_RSHIFT
              PYOP_BINARY_AND
              PYOP_BINARY_XOR
              PYOP_BINARY_OR
              PYOP_INPLACE_POWER
              PYOP_GET_ITER
              PYOP_GET_YIELD_FROM_ITER
              PYOP_PRINT_EXPR
              PYOP_LOAD_BUILD_CLASS
              PYOP_YIELD_FROM
              PYOP_GET_AWAITABLE
              PYOP_LOAD_ASSERTION_ERROR
              PYOP_INPLACE_LSHIFT
              PYOP_INPLACE_RSHIFT
              PYOP_INPLACE_AND
              PYOP_INPLACE_XOR
              PYOP_INPLACE_OR
              PYOP_LIST_TO_TUPLE
              PYOP_RETURN_VALUE
              PYOP_IMPORT_STAR
              PYOP_SETUP_ANNOTATIONS
              PYOP_YIELD_VALUE
              PYOP_POP_BLOCK
              PYOP_POP_EXCEPT
              PYOP_HAVE_ARGUMENT
              PYOP_STORE_NAME
              PYOP_DELETE_NAME
              PYOP_UNPACK_SEQUENCE
              PYOP_FOR_ITER
              PYOP_UNPACK_EX
              PYOP_STORE_ATTR
              PYOP_DELETE_ATTR
              PYOP_STORE_GLOBAL
              PYOP_DELETE_GLOBAL
              PYOP_LOAD_CONST
              PYOP_LOAD_NAME
              PYOP_BUILD_TUPLE
              PYOP_BUILD_LIST
              PYOP_BUILD_SET
              PYOP_BUILD_MAP
              PYOP_LOAD_ATTR
              PYOP_COMPARE_OP
              PYOP_IMPORT_NAME
              PYOP_IMPORT_FROM
              PYOP_JUMP_FORWARD
              PYOP_JUMP_IF_FALSE_OR_POP
              PYOP_JUMP_IF_TRUE_OR_POP
              PYOP_JUMP_ABSOLUTE
              PYOP_POP_JUMP_IF_FALSE
              PYOP_POP_JUMP_IF_TRUE
              PYOP_LOAD_GLOBAL
              PYOP_IS_OP
              PYOP_CONTAINS_OP
              PYOP_JUMP_IF_NOT_EXC_MATCH
              PYOP_SETUP_FINALLY
              PYOP_LOAD_FAST
              PYOP_STORE_FAST
              PYOP_DELETE_FAST
              PYOP_RAISE_VARARGS
              PYOP_CALL_FUNCTION
              PYOP_MAKE_FUNCTION
              PYOP_BUILD_SLICE
              PYOP_LOAD_CLOSURE
              PYOP_LOAD_DEREF
              PYOP_STORE_DEREF
              PYOP_DELETE_DEREF
              PYOP_CALL_FUNCTION_KW
              PYOP_CALL_FUNCTION_EX
              PYOP_SETUP_WITH
              PYOP_EXTENDED_ARG
              PYOP_LIST_APPEND
              PYOP_SET_ADD
              PYOP_MAP_ADD
              PYOP_LOAD_CLASSDEREF
              PYOP_SETUP_ASYNC_WITH
              PYOP_FORMAT_VALUE
              PYOP_BUILD_CONST_KEY_MAP
              PYOP_BUILD_STRING
              PYOP_LOAD_METHOD
              PYOP_CALL_METHOD
              PYOP_LIST_EXTEND
              PYOP_SET_UPDATE
              PYOP_DICT_MERGE
              PYOP_DICT_UPDATE
              PYOP_EXCEPT_HANDLER
              ))
